export const INFOR_TYPE_LIST = [
  'NATIONAL_SECURITY',
  'FORBIDDEN_PROPERTY',
  'HIGH_TECHNOLOGY',
  'CORRUPTION',
  'DRUG_ENVIRONMENT_CRIMINAL',
];

export const INFOR_STATUS_LIST = ['PROCESSING', 'CLOSED_NOT_FINISHED', 'CLOSED_FINISHED'];
